<?php

/**
 * @file
 * Primary module hooks for Spotify API module.
 */

function spotify_api_theme() {
  return [
    'spotify_api_artists' => [
      'variables' => [
        'header' => NULL,
        'artists' => NULL,
        'no_results' => NULL,
      ],
    ],
    'spotify_api_artist' => [
      'variables' => [
        'name' => NULL,
        'image' => NULL,
        'genres' => NULL,
      ],
    ],
  ];
}
