<?php

/**
 * @file
 * Primary module hooks for Spotify API module.
 */

function spotify_api_theme() {
  return [
    'spotify_api_artists' => [
      'variables' => [
        'header' => NULL,
        'artists' => NULL,
        'no_results' => NULL,
      ],
    ],
    'spotify_api_artist' => [
      'variables' => [
        'link' => NULL,
        'name' => NULL,
        'image_url' => NULL,
        'image_width' => NULL,
        'genres' => NULL,
      ],
    ],
  ];
}
